# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

# Text to speech
tts:
  - platform: google_translate

frontend: !include frontend.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
      exclude_domains:
        - media_player

device_tracker:
  - platform: netgear
    password: !secret router_pw
    port: 80
    accesspoints:

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

sensor:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    forecast:
      - 0
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - icon
      - temperature

tplink:

zha:
  usb_path: /dev/ttyUSB1
